version: 2.1
orbs: 
    python: circleci/python@2.1.1
jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.9
    steps:
      - checkout
      - run: 
          command: |
            pip install pytest
            cd csv-combiner
            python3 test_csv_combiner.py
      - store_test_results:
          path: test-results
workflows:
  testing_csv_combiner:
    jobs:
      - build-and-test